export const data = [
  {
    name: "Spaghetti Carbonara",
    provider: "Chef Mario",
    totalRatings: 500,
    avgRating: 4.8,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Pasta",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A classic Italian pasta dish with a creamy egg-based sauce and crispy pancetta.",
    imgUrl: "https://i.pinimg.com/564x/a9/0e/e4/a90ee4bca901e935a7a406a7d90ca6c2.jpg"
  },
  {
    name: "Vegan Bowl",
    provider: "Chef Lisa",
    totalRatings: 300,
    avgRating: 4.6,
    dateProvided: "2025-02-22",
    mealType: "Breakfast",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A nourishing bowl with quinoa, roasted veggies, and a zesty tahini dressing.",
    imgUrl: "https://i.pinimg.com/236x/27/00/d3/2700d3830322800332d3a57aa7c2a8f3.jpg"
  },
  {
    name: "Chicken Tikka Masala",
    provider: "chef Kichcha",
    totalRatings: 750,
    avgRating: 4.7,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Curry",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Tender chicken pieces in a rich, creamy tomato-based sauce, served with rice.",
    imgUrl: "https://i.pinimg.com/564x/c6/65/c7/c665c758a0b5d5a6a93db951d11124d1.jpg"
  },
  
  {
    name: "Gobi Manchuri",
    provider: "chef Shivanand",
    totalRatings: 450,
    avgRating: 4.5,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Stew",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A hearty Chinese dish with Cauliflower.",
    imgUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/gobi-manchurian.jpg"
  },
  {
    name: "Classic Margherita Pizza",
    provider: "Chef Antonio",
    totalRatings: 800,
    avgRating: 4.9,
    dateProvided: "2024-03-01",
    mealType: "Dinner",
    dishType: "Pizza",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A simple yet delicious pizza with fresh tomatoes, mozzarella, and basil.",
    imgUrl: "https://i.pinimg.com/236x/f5/f4/9d/f5f49dea66fcf93b932c8238b68e4f5e.jpg"
  },
  {
    name: "Shrimp Scampi",
    provider: "Chef Dominic",
    totalRatings: 350,
    avgRating: 4.4,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Seafood",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "Juicy shrimp cooked in a garlic butter sauce, served over linguine.",
    imgUrl: "https://i.pinimg.com/236x/28/ce/17/28ce174405ff4903aeaccf3cb082c8ce.jpg"
  },
  
  {
    name: "Lemon Garlic Salmon",
    provider: "Chef Oliver",
    totalRatings: 480,
    avgRating: 4.8,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Seafood",
    testKitchenApproved: true,
    contestWinner: true,
    featured: false,
    description: "Salmon fillets baked with a lemon garlic butter sauce, served with asparagus.",
    imgUrl: "https://i.pinimg.com/736x/45/67/85/4567856f7cd81ff0e547fe66253634cf.jpg"
  },
  {
    name: "Vegetarian Chili",
    provider: "Chef Max",
    totalRatings: 320,
    avgRating: 4.5,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Stew",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A hearty chili made with beans, vegetables, and spices, perfect for vegetarians.",
    imgUrl: "https://i.pinimg.com/564x/8a/20/6e/8a206ecaffdec38456b739b460006492.jpg"
  },
  {
    name: "Mango Smoothie Bowl",
    provider: "Chef Nina",
    totalRatings: 270,
    avgRating: 4.6,
    dateProvided: "2025-02-22",
    mealType: "Breakfast",
    dishType: "Smoothie",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A tropical smoothie bowl topped with fresh mango, granola, and coconut flakes.",
    imgUrl: "https://i.pinimg.com/564x/21/35/df/2135df6a541d814d9da84aa20a19a656.jpg"
  },
  {
    name: "BBQ Ribs",
    provider: "Chef Sam",
    totalRatings: 520,
    avgRating: 4.7,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "BBQ",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Tender and flavorful ribs cooked to perfection with a smoky BBQ sauce.",
    imgUrl: "https://i.pinimg.com/564x/96/7e/3d/967e3de97839af8175b0a008b0128bd0.jpg"
  },
  {
    name: "Parmesan Eggplant",
    provider: "Chef Phantom",
    totalRatings: 310,
    avgRating: 4.4,
    dateProvided: "2023-09-12",
    mealType: "Dinner",
    dishType: "Vegetarian",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "Layers of breaded eggplant, marinara sauce, and melted cheese, baked to perfection.",
    imgUrl: "https://i.pinimg.com/564x/55/51/ea/5551ea01ff93eb81e63845f1e150cb25.jpg"
  },
  {
    name: "Fajitas",
    provider: "Chef Rona",
    totalRatings: 490,
    avgRating: 4.8,
    dateProvided: "2025-02-22",
    mealType: "Dinner",
    dishType: "Mexican",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Sizzling chicken strips with bell peppers and onions, served with tortillas.",
    imgUrl: "https://i.pinimg.com/564x/2c/45/d2/2c45d292d8aa94bc74724fd5c8821444.jpg"
  },
  {
    name: "Avocado Roast",
    provider: "Chef Alex",
    totalRatings: 280,
    avgRating: 4.6,
    dateProvided: "2025-02-22",
    mealType: "Breakfast",
    dishType: "Toast",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "Creamy avocado spread on toasted bread, topped with radishes and a sprinkle of salt.",
    imgUrl: "https://i.pinimg.com/736x/28/38/af/2838af0bd12dd22ebef14cbc6cf6d7cc.jpg"
  },
  {
    name: "Chocolate Lava Cake",
    provider: "Chef Christopher",
    totalRatings: 600,
    avgRating: 4.9,
    dateProvided: "2025-02-22",
    mealType: "Dessert",
    dishType: "Cake",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A decadent dessert with a gooey chocolate center, perfect for chocoholics.",
    imgUrl: "https://i.pinimg.com/474x/1d/06/9d/1d069d96c49b162c06b0d7b7c382937d.jpg"
  },
  {
    name: "Veg Salad",
    provider: "Chef Laura",
    totalRatings: 200,
    avgRating: 4.5,
    dateProvided: "2025-02-22",
    mealType: "Appetizer",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A refreshing salad with ripe tomatoes, mozzarella, basil, and balsamic glaze.",
    imgUrl: "https://i.pinimg.com/236x/0f/1b/12/0f1b12f0be0ddc62082aebdf2a965c8a.jpg"
  },
  {
    name: "French Onion Soup",
    provider: "Chef Jacques",
    totalRatings: 400,
    avgRating: 4.7,
    dateProvided: "2025-02-22",
    mealType: "Appetizer",
    dishType: "Soup",
    testKitchenApproved: true,
    contestWinner: true,
    featured: false,
    description: "A rich and savory soup with caramelized onions and melted cheese.",
    imgUrl: "https://i.pinimg.com/564x/f0/38/35/f0383551510a637664c4def95054218e.jpg"
  },
  {
    name: "Grilled Chicken ",
    provider: "Chef Hannah",
    totalRatings: 550,
    avgRating: 4.6,
    dateProvided: "2025-02-22",
    mealType: "Lunch",
    dishType: "Salad",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A classic Caesar salad topped with juicy grilled chicken and croutons.",
    imgUrl: "https://i.pinimg.com/564x/6e/e3/3c/6ee33ce79716c81f5a4ae96631c616d8.jpg"
  },
];
